AFL->FOT no source

diff --git a/afl-cmin b/afl-cmin
--- a/afl-cmin
+++ b/afl-cmin
@@ -49,7 +49,7 @@ MEM_LIMIT=100
 TIMEOUT=none
 
 unset IN_DIR OUT_DIR STDIN_FILE EXTRA_PAR MEM_LIMIT_GIVEN \
-  AFL_CMIN_CRASHES_ONLY AFL_CMIN_ALLOW_ANY QEMU_MODE
+  FOT_CMIN_CRASHES_ONLY FOT_CMIN_ALLOW_ANY QEMU_MODE
 
 while getopts "+i:o:f:m:t:eQC" opt; do
 
@@ -76,7 +76,7 @@ while getopts "+i:o:f:m:t:eQC" opt; do
          EXTRA_PAR="$EXTRA_PAR -e"
          ;;
     "C")
-         export AFL_CMIN_CRASHES_ONLY=1
+         export FOT_CMIN_CRASHES_ONLY=1
          ;;
     "Q")
          EXTRA_PAR="$EXTRA_PAR -Q"
@@ -126,7 +126,7 @@ fi
 # Do a sanity check to discourage the use of /tmp, since we can't really
 # handle this safely from a shell script.
 
-if [ "$AFL_ALLOW_TMP" = "" ]; then
+if [ "$FOT_ALLOW_TMP" = "" ]; then
 
   echo "$IN_DIR" | grep -qE '^(/var)?/tmp/'
   T1="$?"
@@ -196,9 +196,9 @@ if [ ! -f "$TARGET_BIN" -o ! -x "$TARGET_BIN" ]; then
 
 fi
 
-if [ "$AFL_SKIP_BIN_CHECK" = "" -a "$QEMU_MODE" = "" ]; then
+if [ "$FOT_SKIP_BIN_CHECK" = "" -a "$QEMU_MODE" = "" ]; then
 
-  if ! grep -qF "__AFL_SHM_ID" "$TARGET_BIN"; then
+  if ! grep -qF "__FOT_SHM_ID" "$TARGET_BIN"; then
     echo "[-] Error: binary '$TARGET_BIN' doesn't appear to be instrumented." 1>&2
     exit 1
   fi
@@ -229,14 +229,14 @@ if [ ! "$STDIN_FILE" = "" ]; then
   touch "$STDIN_FILE" || exit 1
 fi
 
-if [ "$AFL_PATH" = "" ]; then
+if [ "$FOT_PATH" = "" ]; then
   SHOWMAP="${0%/afl-cmin}/afl-showmap"
 else
-  SHOWMAP="$AFL_PATH/afl-showmap"
+  SHOWMAP="$FOT_PATH/afl-showmap"
 fi
 
 if [ ! -x "$SHOWMAP" ]; then
-  echo "[-] Error: can't find 'afl-showmap' - please set AFL_PATH." 1>&2
+  echo "[-] Error: can't find 'afl-showmap' - please set FOT_PATH." 1>&2
   rm -rf "$TRACE_DIR"
   exit 1
 fi
@@ -274,12 +274,12 @@ echo "[*] Testing the target binary..."
 
 if [ "$STDIN_FILE" = "" ]; then
 
-  AFL_CMIN_ALLOW_ANY=1 "$SHOWMAP" -m "$MEM_LIMIT" -t "$TIMEOUT" -o "$TRACE_DIR/.run_test" -Z $EXTRA_PAR -- "$@" <"$IN_DIR/$FIRST_FILE"
+  FOT_CMIN_ALLOW_ANY=1 "$SHOWMAP" -m "$MEM_LIMIT" -t "$TIMEOUT" -o "$TRACE_DIR/.run_test" -Z $EXTRA_PAR -- "$@" <"$IN_DIR/$FIRST_FILE"
 
 else
 
   cp "$IN_DIR/$FIRST_FILE" "$STDIN_FILE"
-  AFL_CMIN_ALLOW_ANY=1 "$SHOWMAP" -m "$MEM_LIMIT" -t "$TIMEOUT" -o "$TRACE_DIR/.run_test" -Z $EXTRA_PAR -A "$STDIN_FILE" -- "$@" </dev/null
+  FOT_CMIN_ALLOW_ANY=1 "$SHOWMAP" -m "$MEM_LIMIT" -t "$TIMEOUT" -o "$TRACE_DIR/.run_test" -Z $EXTRA_PAR -A "$STDIN_FILE" -- "$@" </dev/null
 
 fi
 
@@ -292,7 +292,7 @@ if [ "$FIRST_COUNT" -gt "0" ]; then
 else
 
   echo "[-] Error: no instrumentation output detected (perhaps crash or timeout)." 1>&2
-  test "$AFL_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
+  test "$FOT_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
   exit 1
 
 fi
@@ -399,7 +399,7 @@ sort -k1,1 -s -u "$TRACE_DIR/.candidate_list" | \
 
 if [ ! -s "$TRACE_DIR/.candidate_script" ]; then
   echo "[-] Error: no traces obtained from test cases, check syntax!" 1>&2
-  test "$AFL_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
+  test "$FOT_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
   exit 1
 fi
 
@@ -456,6 +456,6 @@ fi
 echo "[+] Narrowed down to $OUT_COUNT files, saved in '$OUT_DIR'."
 echo
 
-test "$AFL_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
+test "$FOT_KEEP_TRACES" = "" && rm -rf "$TRACE_DIR"
 
 exit 0
diff --git a/experimental/clang_asm_normalize/as b/experimental/clang_asm_normalize/as
--- a/experimental/clang_asm_normalize/as
+++ b/experimental/clang_asm_normalize/as
@@ -19,32 +19,32 @@
 #
 # Usage:
 #
-# export AFL_REAL_PATH=/path/to/directory/with/afl-as/
-# AFL_PATH=/path/to/this/directory/ make clean all
+# export FOT_REAL_PATH=/path/to/directory/with/afl-as/
+# FOT_PATH=/path/to/this/directory/ make clean all
 
 if [ "$#" -lt "2" ]; then
   echo "[-] Error: this utility can't be called directly." 1>&2
   exit 1
 fi
 
-if [ "$AFL_REAL_PATH" = "" ]; then
-  echo "[-] Error: AFL_REAL_PATH not set!" 1>&2
+if [ "$FOT_REAL_PATH" = "" ]; then
+  echo "[-] Error: FOT_REAL_PATH not set!" 1>&2
   exit 1
 fi
 
-if [ ! -x "$AFL_REAL_PATH/afl-as" ]; then
-  echo "[-] Error: AFL_REAL_PATH does not contain the 'afl-as' binary." 1>&2
+if [ ! -x "$FOT_REAL_PATH/afl-as" ]; then
+  echo "[-] Error: FOT_REAL_PATH does not contain the 'afl-as' binary." 1>&2
   exit 1
 fi
 
-unset __AFL_AS_CMDLINE __AFL_FNAME
+unset __FOT_AS_CMDLINE __FOT_FNAME
 
 while [ ! "$#" = "0" ]; do
 
   if [ "$#" = "1" ]; then
-    __AFL_FNAME="$1"
+    __FOT_FNAME="$1"
   else
-    __AFL_AS_CMDLINE="${__AFL_AS_CMDLINE} $1"
+    __FOT_AS_CMDLINE="${__FOT_AS_CMDLINE} $1"
   fi
 
   shift
@@ -57,7 +57,7 @@ TMPFILE=`mktemp $TMPDIR/.afl-XXXXXXXXXX.s`
 
 test "$TMPFILE" = "" && exit 1
 
-clang -cc1as -filetype asm -output-asm-variant 0 "${__AFL_FNAME}" >"$TMPFILE"
+clang -cc1as -filetype asm -output-asm-variant 0 "${__FOT_FNAME}" >"$TMPFILE"
 
 ERR="$?"
 
@@ -66,7 +66,7 @@ if [ ! "$ERR" = "0" ]; then
   exit $ERR
 fi
 
-"$AFL_REAL_PATH/afl-as" ${__AFL_AS_CMDLINE} "$TMPFILE"
+"$FOT_REAL_PATH/afl-as" ${__FOT_AS_CMDLINE} "$TMPFILE"
 
 ERR="$?"
 
