afl->fafl

diff --git a/fafl-cmin b/fafl-cmin
--- a/fafl-cmin
+++ b/fafl-cmin
@@ -18,25 +18,25 @@
 # the starting corpus. This has two uses:
 #
 #   - Screening large corpora of input files before using them as a seed for
-#     afl-fuzz. The tool will remove functionally redundant files and likely
+#     fafl-fuzz. The tool will remove functionally redundant files and likely
 #     leave you with a much smaller set.
 #
-#     (In this case, you probably also want to consider running afl-tmin on
+#     (In this case, you probably also want to consider running fafl-tmin on
 #     the individual files later on to reduce their size.)
 #
-#   - Minimizing the corpus generated organically by afl-fuzz, perhaps when
+#   - Minimizing the corpus generated organically by fafl-fuzz, perhaps when
 #     planning to feed it to more resource-intensive tools. The tool achieves
 #     this by removing all entries that used to trigger unique behaviors in the
 #     past, but have been made obsolete by later finds.
 #
 # Note that the tool doesn't modify the files themselves. For that, you want
-# afl-tmin.
+# fafl-tmin.
 #
 # This script must use bash because other shells may have hardcoded limits on
 # array sizes.
 #
 
-echo "corpus minimization tool for afl-fuzz by <lcamtuf@google.com>"
+echo "corpus minimization tool for fafl-fuzz by <lcamtuf@google.com>"
 echo
 
 #########
@@ -230,13 +230,13 @@ if [ ! "$STDIN_FILE" = "" ]; then
 fi
 
 if [ "$FOT_PATH" = "" ]; then
-  SHOWMAP="${0%/afl-cmin}/afl-showmap"
+  SHOWMAP="${0%/fafl-cmin}/fafl-showmap"
 else
-  SHOWMAP="$FOT_PATH/afl-showmap"
+  SHOWMAP="$FOT_PATH/fafl-showmap"
 fi
 
 if [ ! -x "$SHOWMAP" ]; then
-  echo "[-] Error: can't find 'afl-showmap' - please set FOT_PATH." 1>&2
+  echo "[-] Error: can't find 'fafl-showmap' - please set FOT_PATH." 1>&2
   rm -rf "$TRACE_DIR"
   exit 1
 fi
@@ -267,7 +267,7 @@ else
   CP_TOOL=cp
 fi
 
-# Make sure that we can actually get anything out of afl-showmap before we
+# Make sure that we can actually get anything out of fafl-showmap before we
 # waste too much time.
 
 echo "[*] Testing the target binary..."
diff --git a/llvm_mode/Makefile b/llvm_mode/Makefile
--- a/llvm_mode/Makefile
+++ b/llvm_mode/Makefile
@@ -17,7 +17,7 @@
 #
 
 PREFIX      ?= /usr/local
-HELPER_PATH  = $(PREFIX)/lib/afl
+HELPER_PATH  = $(PREFIX)/lib/fafl
 BIN_PATH     = $(PREFIX)/bin
 
 VERSION     = $(shell grep '^\#define VERSION ' ../config.h | cut -d '"' -f2)
@@ -59,9 +59,9 @@ ifeq "$(origin CC)" "default"
 endif
 
 ifndef FOT_TRACE_PC
-  PROGS      = ../afl-clang-fast ../afl-llvm-pass.so ../afl-llvm-rt.o ../afl-llvm-rt-32.o ../afl-llvm-rt-64.o
+  PROGS      = ../fafl-clang-fast ../fafl-llvm-pass.so ../fafl-llvm-rt.o ../fafl-llvm-rt-32.o ../fafl-llvm-rt-64.o
 else
-  PROGS      = ../afl-clang-fast ../afl-llvm-rt.o ../afl-llvm-rt-32.o ../afl-llvm-rt-64.o
+  PROGS      = ../fafl-clang-fast ../fafl-llvm-rt.o ../fafl-llvm-rt-32.o ../fafl-llvm-rt-64.o
 endif
 
 all: test_deps $(PROGS) test_build all_done
@@ -75,42 +75,42 @@ else
 endif
 	@echo "[*] Checking for working '$(CC)'..."
 	@which $(CC) >/dev/null 2>&1 || ( echo "[-] Oops, can't find '$(CC)'. Make sure that it's in your \$$PATH (or set \$$CC and \$$CXX)."; exit 1 )
-	@echo "[*] Checking for '../afl-showmap'..."
-	@test -f ../afl-showmap || ( echo "[-] Oops, can't find '../afl-showmap'. Be sure to compile FOT first."; exit 1 )
+	@echo "[*] Checking for '../fafl-showmap'..."
+	@test -f ../fafl-showmap || ( echo "[-] Oops, can't find '../fafl-showmap'. Be sure to compile FOT first."; exit 1 )
 	@echo "[+] All set and ready to build."
 
-../afl-clang-fast: afl-clang-fast.c | test_deps
+../fafl-clang-fast: fafl-clang-fast.c | test_deps
 	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)
-	ln -sf afl-clang-fast ../afl-clang-fast++
+	ln -sf fafl-clang-fast ../fafl-clang-fast++
 
-../afl-llvm-pass.so: afl-llvm-pass.so.cc | test_deps
+../fafl-llvm-pass.so: fafl-llvm-pass.so.cc | test_deps
 	$(CXX) $(CLANG_CFL) -shared $< -o $@ $(CLANG_LFL)
 
-../afl-llvm-rt.o: afl-llvm-rt.o.c | test_deps
+../fafl-llvm-rt.o: fafl-llvm-rt.o.c | test_deps
 	$(CC) $(CFLAGS) -fPIC -c $< -o $@
 
-../afl-llvm-rt-32.o: afl-llvm-rt.o.c | test_deps
+../fafl-llvm-rt-32.o: fafl-llvm-rt.o.c | test_deps
 	@printf "[*] Building 32-bit variant of the runtime (-m32)... "
 	@$(CC) $(CFLAGS) -m32 -fPIC -c $< -o $@ 2>/dev/null; if [ "$$?" = "0" ]; then echo "success!"; else echo "failed (that's fine)"; fi
 
-../afl-llvm-rt-64.o: afl-llvm-rt.o.c | test_deps
+../fafl-llvm-rt-64.o: fafl-llvm-rt.o.c | test_deps
 	@printf "[*] Building 64-bit variant of the runtime (-m64)... "
 	@$(CC) $(CFLAGS) -m64 -fPIC -c $< -o $@ 2>/dev/null; if [ "$$?" = "0" ]; then echo "success!"; else echo "failed (that's fine)"; fi
 
 test_build: $(PROGS)
 	@echo "[*] Testing the CC wrapper and instrumentation output..."
-	unset FOT_USE_ASAN FOT_USE_MSAN FOT_INST_RATIO; FOT_QUIET=1 FOT_PATH=. FOT_CC=$(CC) ../afl-clang-fast $(CFLAGS) ../test-instr.c -o test-instr $(LDFLAGS)
-	echo 0 | ../afl-showmap -m none -q -o .test-instr0 ./test-instr
-	echo 1 | ../afl-showmap -m none -q -o .test-instr1 ./test-instr
+	unset FOT_USE_ASAN FOT_USE_MSAN FOT_INST_RATIO; FOT_QUIET=1 FOT_PATH=. FOT_CC=$(CC) ../fafl-clang-fast $(CFLAGS) ../test-instr.c -o test-instr $(LDFLAGS)
+	echo 0 | ../fafl-showmap -m none -q -o .test-instr0 ./test-instr
+	echo 1 | ../fafl-showmap -m none -q -o .test-instr1 ./test-instr
 	@rm -f test-instr
 	@cmp -s .test-instr0 .test-instr1; DR="$$?"; rm -f .test-instr0 .test-instr1; if [ "$$DR" = "0" ]; then echo; echo "Oops, the instrumentation does not seem to be behaving correctly!"; echo; echo "Please ping <lcamtuf@google.com> to troubleshoot the issue."; echo; exit 1; fi
 	@echo "[+] All right, the instrumentation seems to be working!"
 
 all_done: test_build
-	@echo "[+] All done! You can now use '../afl-clang-fast' to compile programs."
+	@echo "[+] All done! You can now use '../fafl-clang-fast' to compile programs."
 
 .NOTPARALLEL: clean
 
 clean:
 	rm -f *.o *.so *~ a.out core core.[1-9][0-9]* test-instr .test-instr0 .test-instr1 
-	rm -f $(PROGS) ../afl-clang-fast++
+	rm -f $(PROGS) ../fafl-clang-fast++
